services:
  - type: web
    name: gamelog
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && flask --app app seed && (flask --app app import-games --limite 40 || true) && gunicorn "app:create_app()" --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
